#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := img_viewer
USER_PATH := $(abspath $(shell pwd)/)
include $(USER_PATH)/components/component_conf.mk
include $(IDF_PATH)/make/project.mk

